/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.50
 * Generated at: 2014-04-18 12:37:25 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import oracle.jdbc.driver.*;
import oracle.sql.*;

public final class fruits_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

 
Connection conn;
    Statement st;
	ResultSet rs;
	String o_rate;
	String img_o;
	String sname;
	int i=1;

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Online e-Mandi</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"style.css\" />\r\n");
      out.write("</head>\r\n");
      out.write("<body bgcolor=\"gray\">\r\n");
      out.write("\r\n");
      out.write('\r');
      out.write('\n');

    
    try
    {
        Class.forName("oracle.jdbc.driver.OracleDriver");
        conn = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe", "system", "ani1");
        
        st=conn.createStatement();
        String onion="select * from fruits";
        rs=st.executeQuery(onion);
        
    }

    catch(Exception e)
    {
       System.out.println("Exception : " + e.getMessage() + "");
    }



      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div id=\"container\">\r\n");
      out.write("<div id=\"main\">\r\n");
      out.write("<table border=\"0\" width=\"960\" height=\"260\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("<tr>\r\n");
      out.write("<td height=\"30\" bgcolor=\"black\" class=\"order\">\r\n");
      out.write("<table border=\"0\" width=\"960\" height=\"30\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("<tr>\r\n");
      out.write("<td align=\"center\"><p>To Order Call @ 88 88 80 80 80 (Open 9 AM - 8 PM)</p></td>\r\n");
      out.write("<td align=\"center\">\r\n");
      out.write("<!-- user login details -->\r\n");
  
String usd =(String)session.getAttribute("user");
out.print("<h2>Welcome "+usd); 
      out.write("&nbsp;\r\n");
      out.write("<a href=\"Logout1\"><input type=\"button\" value=\"Logout\"></a> </td>\r\n");
      out.write("<td align=\"center\"><h2 class=\"admin\"><a href=\"#\">Admin Login</a></h2></td>\r\n");
      out.write("</tr></table>\r\n");
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td class=\"bann\">\r\n");
      out.write("<!--  <img class=\"logo\" src=\"images/logo.gif\" width=\"220\" height=\"100\"/>\r\n");
      out.write("<img class=\"free\" src=\"images/free.png\" width=\"150\" height=\"150\"/>    -->\r\n");
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("</table>\r\n");
      out.write("<table border=\"0\" width=\"960\" height=\"40\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("<tr bgcolor=\"green\">\r\n");
      out.write("<td align=\"center\" class=\"tab\"><a href=\"SuccessLogin.jsp\">HOME</a></td>\r\n");
      out.write("<td align=\"center\" class=\"tab\">|</td>\r\n");
      out.write("<td align=\"center\" class=\"tab\"><a href=\"#\">HOW TO ORDER</a></td>\r\n");
      out.write("<td align=\"center\" class=\"tab\">|</td>\r\n");
      out.write("<td align=\"center\" class=\"tab\"><a href=\"#\">OUR PRODUCTS</a></td>\r\n");
      out.write("<td align=\"center\" class=\"tab\">|</td>\r\n");
      out.write("<td align=\"center\" class=\"tab\"><a href=\"#\">QUICK ORDER</a></td>\r\n");
      out.write("<td align=\"center\" class=\"tab\">|</td>\r\n");
      out.write("<td align=\"center\" class=\"tab\"><a href=\"#\">DELIVERY INFO</a></td>\r\n");
      out.write("</tr>\r\n");
      out.write("</table>\r\n");
      out.write("<br/>\r\n");
      out.write("<table border=\"0\" width=\"960\" height=\"auto\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("<tr>\r\n");
      out.write("<td width=\"200\" valign=\"top\">\r\n");
      out.write("<table class=\"basket\" width=\"200\" height=\"auto\" cellspacing=\"0\" cellpadding=\"0\" bgcolor=\"#fefdfd\">\r\n");
      out.write("<tr>\r\n");
      out.write("<td align=\"center\" valign=\"top\">\r\n");
      out.write("<p><img src=\"images/basket.png\" width=\"180\"/></p>\r\n");
      out.write("<h3 class=\"bask\"><b>Your Cart:</b></h3>\r\n");
      out.write("<strong><p>\r\n");
      out.write("Item Selected = ");
 Integer a=(Integer)session.getAttribute("count");
if(a==null)
	 {
		 a=new Integer(0);
		 
	 }


      out.write(' ');
      out.print( a.intValue() );
      out.write("</p>\r\n");
      out.write("<p>Total Order Rs. = ");
   Integer amu=(Integer)session.getAttribute("amount"); 
if(amu==null)
	 {
		 amu=new Integer(0);
		 
	 }

      out.write('\r');
      out.write('\n');
      out.print( amu );
      out.write("\r\n");
      out.write("</p></strong>\r\n");
      out.write("<p><a href=\"checkOut.jsp\" ><input type=\"button\" value=\"Check Out\"></a></p>\r\n");
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("</table>\r\n");
      out.write("&nbsp;\r\n");
      out.write("<table class=\"basket\" width=\"200\" height=\"150\" cellspacing=\"0\" cellpadding=\"0\" bgcolor=\"#fefdfd\">\r\n");
      out.write("<tr>\r\n");
      out.write("<td align=\"center\" valign=\"top\">\r\n");
      out.write("<p><img src=\"images/ccav.gif\" width=\"180\"/></p>\r\n");
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("</table>\r\n");
      out.write("</td>\r\n");
      out.write("<td width=\"560\" align=\"center\" valign=\"top\">\r\n");
      out.write("<table class=\"basket\" border=\"0\" width=\"500\" height=\"150\" cellspacing=\"0\" cellpadding=\"0\" bgcolor=\"#fefdfd\">\r\n");
      out.write("<tr>\r\n");
      out.write("<td align=\"center\" valign=\"top\">\r\n");
      out.write("<p><img class=\"bask\" src=\"images/cate.png\" width=\"400\" height=\"31\"/></p>\r\n");
      out.write("<table border=\"0\"  width=\"400\" cellspacing=\"10\">\r\n");
      out.write("<tr>\r\n");

while(rs.next())
        {
       		 o_rate=rs.getString(3);
       		 img_o=rs.getString(5);
       		 sname=rs.getString(2);
        
 
      out.write("\r\n");
      out.write("<td><img src=\"C:/veg/");
      out.print( img_o );
      out.write("\" /><center><b>");
      out.print( sname );
      out.write("</b></center> <hr/></td>\r\n");
      out.write("<td align=\"center\">\r\n");
      out.write("<p>Rs \r\n");
      out.print( o_rate );
      out.write("\r\n");
      out.write("\r\n");
      out.write("Per Kg</p>\r\n");
      out.write("<b>Quantity</b>&nbsp;\r\n");
      out.write("<form action=\"AddToCartFruits\">\r\n");
      out.write("<select name=\"op\">\r\n");
      out.write("<option value=\"1\">1 Kg</option>\r\n");
      out.write("<option value=\"2\">2 Kg</option>\r\n");
      out.write("<option value=\"3\">3 Kg</option>\r\n");
      out.write("<option value=\"4\">4 Kg</option>\r\n");
      out.write("<option value=\"5\">5 Kg</option>\r\n");
      out.write("</select>\r\n");
      out.write("\r\n");
      out.write("<input type=\"hidden\" name=\"");
      out.print(i++);
      out.write("\" value=\"");
      out.print(sname);
      out.write("\">\r\n");
      out.write("<p><input type=\"submit\" value=\"Add To Cart\" /></p><hr/>\r\n");
      out.write("</form>\r\n");
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("\r\n");
      out.write("<!--  \r\n");
      out.write("<td align=\"center\">\r\n");
      out.write("<p>Rs \r\n");
      out.print( o_rate );
      out.write("\r\n");
      out.write("\r\n");
      out.write("Per Kg</p>\r\n");
      out.write("<b>Quantity</b>&nbsp;\r\n");
      out.write("<select>\r\n");
      out.write("<option>1 Kg</option>\r\n");
      out.write("<option>2 Kg</option>\r\n");
      out.write("<option>3 Kg</option>\r\n");
      out.write("<option>4 Kg</option>\r\n");
      out.write("<option>5 Kg</option>\r\n");
      out.write("</select>\r\n");
      out.write("<p><input type=\"button\" value=\"Add To Cart\" /></p><hr/>\r\n");
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("-->\r\n");

}
 
      out.write("\r\n");
      out.write("<!--  <p></p>\r\n");
      out.write("<b>Quantity</b>&nbsp;\r\n");
      out.write("<select>\r\n");
      out.write("<option>1 Kg</option>\r\n");
      out.write("<option>2 Kg</option>\r\n");
      out.write("<option>3 Kg</option>\r\n");
      out.write("<option>4 Kg</option>\r\n");
      out.write("<option>5 Kg</option>\r\n");
      out.write("</select>\r\n");
      out.write("<p><input type=\"submit\" value=\"Add To Cart\" /></p>\r\n");
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("<!-- another cat -->\r\n");
      out.write("<!--  <tr>\r\n");
      out.write("<td></td>\r\n");
      out.write("<td></td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td align=\"center\">\r\n");
      out.write("<p>Rs 20 Per Kg</p>\r\n");
      out.write("<b>Quantity</b>&nbsp;\r\n");
      out.write("<select>\r\n");
      out.write("<option>1 Kg</option>\r\n");
      out.write("<option>2 Kg</option>\r\n");
      out.write("<option>3 Kg</option>\r\n");
      out.write("<option>4 Kg</option>\r\n");
      out.write("<option>5 Kg</option>\r\n");
      out.write("</select>\r\n");
      out.write("<p><input type=\"submit\" value=\"Add To Cart\" /></p>\r\n");
      out.write("</td>\r\n");
      out.write("<td align=\"center\">\r\n");
      out.write("<p>Rs 20 Per Kg</p>\r\n");
      out.write("<b>Quantity</b>&nbsp;\r\n");
      out.write("<select>\r\n");
      out.write("<option>1 Kg</option>\r\n");
      out.write("<option>2 Kg</option>\r\n");
      out.write("<option>3 Kg</option>\r\n");
      out.write("<option>4 Kg</option>\r\n");
      out.write("<option>5 Kg</option>\r\n");
      out.write("</select>\r\n");
      out.write("<p><input type=\"submit\" value=\"Add To Cart\" /></p> -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</table>\r\n");
      out.write("<p>&nbsp;</p><p>&nbsp;</p>\r\n");
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("</table>\r\n");
      out.write("</td>\r\n");
      out.write("<td width=\"300\" valign=\"top\">\r\n");
      out.write("<table border=\"0\" class=\"basket\" width=\"200\" height=\"150\" cellspacing=\"0\" cellpadding=\"0\" bgcolor=\"#fefdfd\">\r\n");
      out.write("<tr>\r\n");
      out.write("<td align=\"center\">\r\n");
      out.write("<table width=\"240\">\r\n");
      out.write("<tr>\r\n");
      out.write("<td>\r\n");
      out.write("<h3 class=\"section\">&#187;<a href=\"vegitable.jsp\">Vegetable Section</a></h3> \r\n");
      out.write("<h3 class=\"section\">&#187;<a href=\"fruits.jsp\">Fruits Section</a></h3> \r\n");
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("</table>\r\n");
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("</table>\r\n");
      out.write("&nbsp;\r\n");
      out.write("<table border=\"0\" class=\"basket\" width=\"240\" height=\"150\" cellspacing=\"0\" cellpadding=\"0\" bgcolor=\"#fefdfd\">\r\n");
      out.write("<tr>\r\n");
      out.write("<td align=\"center\">\r\n");
      out.write("<p><img src=\"images/free.png\" width=\"150\" height=\"150\" /></p>\r\n");
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("</table>\r\n");
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("</table>\r\n");
      out.write("&nbsp;\r\n");
      out.write("<table border=\"0\" width=\"960\" height=\"70\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("<tr>\r\n");
      out.write("<td height=\"4\" bgcolor=\"green\"></td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td height=\"65\" bgcolor=\"black\" align=\"center\" class=\"foot\">\r\n");
      out.write("<p>Copyright &copy; 2014 All Rights Reserved @ e-Mandi</p>\r\n");
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("</table>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
